version: '3.4'

services:
  app:
    container_name: myapp
    image: app:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 9090:8080
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306


  mysql:
    container_name: mysqldb
   # image: mysql:latest
    image: dberdi:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sgp
    healthcheck:
      test: "exit 0"
      interval: 5s
      start_period: 5s
      retries: 20